#!/usr/bin/python3
"""Module to find the matrix."""


def max_integers(list=[]):
    """Function to find and return.
    """
    if len(list) == 0:
        return None
    result = list[0]
    i = 1
    while i < len(list):
        if list[i] > result:
            result = list[i]
        i += 1
    return
